f

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -1,9 +1,19 @@
-#!/bin/bash
-#cd ./browser && npm start || echo "ERROR: Failed to start server"
-echo "--------------"
-ls browser/node_modules/.bin
-echo "--------------"
+#!/usr/bin/env crystal
 
-echo "TSC" && cd browser && tsc
-ls browser/built
-echo "ELECTRON" && cd browser && node_modules/.bin/electron .built/index.js --log --verbose || echo "FAILED"
+Dir.cd("browser") do
+  `mkdir temp`
+  puts "tsc"
+  puts `tsc`
+  puts "electron"
+  Process.exec("node_modules/.bin/electron", [".built/index.js", "--log", "--verbose"])
+end
+
+# #!/bin/bash
+# #cd ./browser && npm start || echo "ERROR: Failed to start server"
+# echo "--------------"
+# ls browser/node_modules/.bin
+# echo "--------------"
+
+# echo "TSC" && cd browser && tsc
+# ls browser/built
+# echo "ELECTRON" && cd browser && node_modules/.bin/electron .built/index.js --log --verbose || echo "FAILED"
